language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '18'
git:
  depth: 3
script:
  - yarn build

deploy:
  provide: pages
  skip-cleanup: true
  keep-history: true
  api_key: $GITHUB_TOKEN
 local-dir: public/
 target-branch: gh-pages
 
on: 
  branch: main